config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :write_ups
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :rate_podcasts
	root 'creatives#index'
	get 'creatives/index'
end

app/models/write_up.rb
class WriteUp < ApplicationRecord
	has_attached_file :image, styles: { medium: "700x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/write_ups_controller.rb
class WriteUpsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_write_up, only: [:show, :edit, :update, :destroy]


  # GET /write_ups
  # GET /write_ups.json
  def index
    @write_ups = WriteUp.all
  end

  # GET /write_ups/1
  # GET /write_ups/1.json
  def show
    @writes_ups = WriteUp.find(params[:id])  
  end

  # GET /write_ups/new
  def new
    @write_up = WriteUp.new
  end

  # GET /write_ups/1/edit
  def edit
  end

  # POST /write_ups
  # POST /write_ups.json
  def create
    @write_up = WriteUp.new(write_up_params)

    respond_to do |format|
      if @write_up.save
        format.html { redirect_to @write_up, notice: 'Write up was successfully created.' }
        format.json { render :show, status: :created, location: @write_up }
      else
        format.html { render :new }
        format.json { render json: @write_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /write_ups/1
  # PATCH/PUT /write_ups/1.json
  def update
    respond_to do |format|
      if @write_up.update(write_up_params)
        format.html { redirect_to @write_up, notice: 'Write up was successfully updated.' }
        format.json { render :show, status: :ok, location: @write_up }
      else
        format.html { render :edit }
        format.json { render json: @write_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /write_ups/1
  # DELETE /write_ups/1.json
  def destroy
    @write_up.destroy
    respond_to do |format|
      format.html { redirect_to write_ups_url, notice: 'Write up was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_write_up
      @write_up = WriteUp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def write_up_params
      params.require(:write_up).permit(:title, :content, :image)
    end
end

app/helpers/write_ups_helper.rb
module WriteUpsHelper
end

app/views/write_ups/_form.html.erb
<%= form_for(write_up) do |f| %>
  <% if write_up.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(write_up.errors.count, "error") %> prohibited this write_up from being saved:</h2>

      <ul>
      <% write_up.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.trix_editor :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/write_ups/edit.html.erb
<section class="write-up-form">
<h1>Editing Write Up</h1>

<%= render 'form', write_up: @write_up %>

<%= link_to 'Show', @write_up %> |
<%= link_to 'Back', write_ups_path %>
</section>

app/views/write_ups/index.html.erb
<%= render 'rate_podcasts/navbar_rating' %>
<!-- <p id="notice"><%= notice %></p> -->
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

  

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/1-col-portfolio.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<header id="intro-header">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading">
                <h1 class="write_up-heading">This Week in Fincasts</h1>
                <h2 class="subheading">Information Distilled</h2>
           
                 
            </div>
        </div>
    </header>




<body class="write_up_body">
    <!-- Page Content -->
    <div class="container">

       


  <!--    <tbody>
    <% @write_ups.each do |write_up| %>
      <tr>
        <td><%= write_up.title %></td>
        <td><%= write_up.content %></td>
        <td><%= link_to 'Show', write_up %></td>
        <td><%= link_to 'Edit', edit_write_up_path(write_up) %></td>
        <td><%= link_to 'Destroy', write_up, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

        

          
      <% @write_ups.each do |write_up| %>
            <!-- Project One -->
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="<%= write_up.image.url(:medium) %>" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3 class="write_up_title"> <%= write_up.title %> </h3>
                <h4 class="write_up_title">Posted <%= time_ago_in_words(write_up.created_at) %> ago</h4>
                <p><%= sanitize(write_up.content.truncate(250, separator: '</p>')) %></p>
                <%=link_to "Read More", write_up, class: "btn btn-primary" %>
            </div>
        </div>
        <!-- /.row -->

        <hr>
      <% end %>

            


        

        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Cambria 2017</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>
<% if can? :create, @write_ups %>
    <%= link_to 'New Write Up', new_write_up_path %>
<% end %>

app/views/write_ups/new.html.erb
<section class="write-up-form">
<h1>New Write Up</h1>

<%= render 'form', write_up: @write_up %>

<%= link_to 'Back', write_ups_path %>
</section>

app/views/write_ups/show.html.erb
<%#<p id="notice"><%= notice %></p>


<%# <%= image_tag @write_up.image.url(:medium) %>


<%# <p>
  <strong>Title:</strong>
  <%= @write_up.title %>
<%# </p>

<p>
  <strong>Content:</strong>
  <%= @write_up.content %>
<%# </p> %>



<%= render 'rate_podcasts/navbar_rating' %>

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">



    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="write_up_body">

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading">
                <h1><%= @write_up.title %></h1>
                <h2 class="subheading">Curated Notes</h2>
                <span class="meta">Posted <%= time_ago_in_words(@write_up.created_at) %> ago
</span>
                 
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container-white">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p class="p-color">
                    <%= simple_format(@write_up.content) %>
                        
                    </p>
                </div>
            </div>
        </div>
    </article>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Cambria 2017</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>
<% if can? :update, @write_up %>
    <%= link_to 'Edit', edit_write_up_path(@write_up) %> |
 <% end %>
 <div class="btn btn-default">  
<%= link_to 'Back', write_ups_path %>
</div>