config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :write_ups
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :rate_podcasts
	root 'creatives#index'
	get 'creatives/index'
end

app/models/rate_podcast.rb
class RatePodcast < ApplicationRecord
	has_attached_file :image, styles: { medium: "700x300>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	ratyrate_rateable "podcast"

end

app/controllers/rate_podcasts_controller.rb
class RatePodcastsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rate_podcast, only: [:show, :edit, :update, :destroy]

  # GET /rate_podcasts
  # GET /rate_podcasts.json
  def index
    @rate_podcasts = RatePodcast.all
  end

  # GET /rate_podcasts/1
  # GET /rate_podcasts/1.json
  def show
    @rate_podcasts = RatePodcast.find(params[:id])  
  end

  # GET /rate_podcasts/new
  def new
    @rate_podcast = RatePodcast.new
  end

  # GET /rate_podcasts/1/edit
  def edit
  end

  # POST /rate_podcasts
  # POST /rate_podcasts.json
  def create
    @rate_podcast = RatePodcast.new(rate_podcast_params)

    respond_to do |format|
      if @rate_podcast.save
        format.html { redirect_to @rate_podcast, notice: 'Rate podcast was successfully created.' }
        format.json { render :show, status: :created, location: @rate_podcast }
      else
        format.html { render :new }
        format.json { render json: @rate_podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rate_podcasts/1
  # PATCH/PUT /rate_podcasts/1.json
  def update
    respond_to do |format|
      if @rate_podcast.update(rate_podcast_params)
        format.html { redirect_to @rate_podcast, notice: 'Rate podcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @rate_podcast }
      else
        format.html { render :edit }
        format.json { render json: @rate_podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rate_podcasts/1
  # DELETE /rate_podcasts/1.json
  def destroy
    @rate_podcast.destroy
    respond_to do |format|
      format.html { redirect_to rate_podcasts_url, notice: 'Rate podcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate_podcast
      @rate_podcast = RatePodcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_podcast_params
      params.require(:rate_podcast).permit(:name, :rating, :image)
    end
end

app/helpers/rate_podcasts_helper.rb
module RatePodcastsHelper
	def rating_for(rateable_obj, dimension=nil, options={})

    cached_average = rateable_obj.average dimension
    avg = cached_average ? cached_average.avg : 0

    star         = options[:star]         || 5
    enable_half  = options[:enable_half]  || false
    half_show    = options[:half_show]    || true
    star_path    = options[:star_path]    || ""
    star_on      = options[:star_on]      || asset_path('star-on.png')
    star_off     = options[:star_off]     || asset_path('star-off.png')
    star_half    = options[:star_half]    || asset_path('star-half.png')
    cancel       = options[:cancel]       || false
    cancel_place = options[:cancel_place] || "left"
    cancel_hint  = options[:cancel_hint]  || "Cancel current rating!"
    cancel_on    = options[:cancel_on]    || asset_path('cancel-on.png')
    cancel_off   = options[:cancel_off]   || asset_path('cancel-off.png')
    noRatedMsg   = options[:noRatedMsg]   || "I'am readOnly and I haven't rated yet!"
    # round        = options[:round]        || { down: .26, full: .6, up: .76 }
    space        = options[:space]        || false
    single       = options[:single]       || false
    target       = options[:target]       || ''
    targetText   = options[:targetText]   || ''
    targetType   = options[:targetType]   || 'hint'
    targetFormat = options[:targetFormat] || '{score}'
    targetScore  = options[:targetScore]  || ''

    disable_after_rate = options[:disable_after_rate] && true
    disable_after_rate = true if disable_after_rate == nil

    if options[:readonly]
      readonly = options[:readonly]
    elsif disable_after_rate
      readonly = !(current_user && rateable_obj.can_rate?(current_user, dimension))
    else
      readonly = !current_user || false
    end

    if options[:imdb_avg] && readonly
      content_tag :div, '', :style => "background-image:url(/assets/mid-star.png);width:61px;height:57px;margin-top:10px;" do
        content_tag :p, avg, :style => "position:relative;font-size:.8rem;text-align:center;line-height:60px;"
      end
    else
      content_tag :div, '', "data-dimension" => dimension, :class => "star", "data-rating" => avg,
                  "data-id" => rateable_obj.id, "data-classname" => rateable_obj.class.name,
                  "data-disable-after-rate" => disable_after_rate,
                  "data-readonly" => readonly,
                  "data-enable-half" => enable_half,
                  "data-half-show" => half_show,
                  "data-star-count" => star,
                  "data-star-path" => star_path,
                  "data-star-on" => star_on,
                  "data-star-off" => star_off,
                  "data-star-half" => star_half,
                  "data-cancel" => cancel,
                  "data-cancel-place" => cancel_place,
                  "data-cancel-hint"  => cancel_hint,
                  "data-cancel-on" => cancel_on,
                  "data-cancel-off" => cancel_off,
                  "data-no-rated-message" => noRatedMsg,
                  # "data-round" => round,
                  "data-space" => space,
                  "data-single" => single,
                  "data-target" => target,
                  "data-target-text" => targetText,
                  "data-target-type" => targetType,
                  "data-target-format" => targetFormat,
                  "data-target-score" => targetScore
    end
  end

  def imdb_style_rating_for(rateable_obj, user, options = {})
    #TODO: add option to change the star icon
    overall_avg = rateable_obj.overall_avg(user)

    content_tag :div, '', :style => "background-image:url(/assets/big-star.png);width:81px;height:81px;margin-top:10px;" do
      content_tag :p, overall_avg, :style => "position:relative;line-height:85px;text-align:center;"
    end
  end

  def rating_for_user(rateable_obj, rating_user, dimension = nil, options = {})
    @object = rateable_obj
    @user   = rating_user
    @rating = Rate.find_by_rater_id_and_rateable_id_and_dimension(@user.id, @object.id, dimension)
    stars = @rating ? @rating.stars : 0

    star         = options[:star]         || 5
    enable_half  = options[:enable_half]  || false
    half_show    = options[:half_show]    || true
    star_path    = options[:star_path]    || ""
    star_on      = options[:star_on]      || asset_path('star-on.png')
    star_off     = options[:star_off]     || asset_path('star-off.png')
    star_half    = options[:star_half]    || asset_path('star-half.png')
    cancel       = options[:cancel]       || false
    cancel_place = options[:cancel_place] || "left"
    cancel_hint  = options[:cancel_hint]  || "Cancel current rating!"
    cancel_on    = options[:cancel_on]    || asset_path('cancel-on.png')
    cancel_off   = options[:cancel_off]   || asset_path('cancel-off.png')
    noRatedMsg   = options[:noRatedMsg]   || "I'am readOnly and I haven't rated yet!"
    # round        = options[:round]        || { down: .26, full: .6, up: .76 }
    space        = options[:space]        || false
    single       = options[:single]       || false
    target       = options[:target]       || ''
    targetText   = options[:targetText]   || ''
    targetType   = options[:targetType]   || 'hint'
    targetFormat = options[:targetFormat] || '{score}'
    targetScore  = options[:targetScore]  || ''

    disable_after_rate = options[:disable_after_rate] || false

    readonly=false
    if disable_after_rate
      readonly = current_user.present? ? !rateable_obj.can_rate?(current_user.id, dimension) : true
    end

    content_tag :div, '', "data-dimension" => dimension, :class => "star", "data-rating" => stars,
                "data-id" => rateable_obj.id, "data-classname" => rateable_obj.class.name,
                "data-disable-after-rate" => disable_after_rate,
                "data-readonly" => readonly,
                "data-enable-half" => enable_half,
                "data-half-show" => half_show,
                "data-star-count" => stars,
                "data-star-path" => star_path,
                "data-star-on" => star_on,
                "data-star-off" => star_off,
                "data-star-half" => star_half,
                "data-cancel" => cancel,
                "data-cancel-place" => cancel_place,
                "data-cancel-hint"  => cancel_hint,
                "data-cancel-on" => cancel_on,
                "data-cancel-off" => cancel_off,
                "data-no-rated-message" => noRatedMsg,
                # "data-round" => round,
                "data-space" => space,
                "data-single" => single,
                "data-target" => target,
                "data-target-text" => targetText,
                "data-target-format" => targetFormat,
                "data-target-score" => targetScore
  end
end

app/views/rate_podcasts/_disqus.html.erb
<div id="disqus_thread"></div>

<script>

(function (document, window, undefined) {

  'use strict';

  // Create button
  var commentsButton = document.createElement('button');

  // Button attrs
  commentsButton.setAttribute('class', 'comments-button');  
  commentsButton.innerHTML = 'Show Comments';

  // Append button to body
  document.body.appendChild(commentsButton);

  // Click event handler
  commentsButton.addEventListener('click', function () {   

    // Create comments container
    var disqusContainer = document.createElement('div'),
      disqus_shortname = 'cambriacuration',
      dsq = document.createElement('script');

    disqusContainer.setAttribute('id', 'disqus_thread');

    // Disqus
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';

    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    
    // Append container to body
    document.body.appendChild(disqusContainer);

    // Remove button
    this.parentNode.removeChild(this);

  }, false);

})(document, window);


</script>

app/views/rate_podcasts/_form.html.erb
<%= form_for(rate_podcast) do |f| %>
  <% if rate_podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rate_podcast.errors.count, "error") %> prohibited this rate_podcast from being saved:</h2>

      <ul>
      <% rate_podcast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rate_podcasts/_navbar_rating.html.erb
<nav id="ratingNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand rate-header" href="/">Cambria Podcast Curation</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="/">Home</a>
                </li>
                <li> <% if user_signed_in? %>
                  <li>
                  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
                  </li>
                <% else %>
                  <li>
                  <%= link_to('Login', new_user_session_path)  %>  
                  </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/rate_podcasts/edit.html.erb
<h1>Editing Rate Podcast</h1>

<%= render 'form', rate_podcast: @rate_podcast %>


<%= link_to 'Show', @rate_podcast %> |
<%= link_to 'Back', rate_podcasts_path %>

app/views/rate_podcasts/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<%= render 'navbar_rating' %>
<!-- <div class="banner">
  <div class="wrapper"> -->
    <header class="ratings-header">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="write_up-heading">
                <h1>This Weeks Ratings</h1>       
            </div>
        </div>
    </header>
  </div>
</div>

<section class="rating-page">
<%= render 'navbar_rating' %>

<div class="container">
  
<div class="user-label"></div>
  <table>
    <thead>
      <tr>
        <th>User Ratings</th>
        <th colspan="3"></th>
      </tr>

    </thead>

    <tbody>
      <% @rate_podcasts.each do |rate_podcast| %>
        <tr>
          <td><%= image_tag rate_podcast.image.url(:thumb), :class => "img_thumb" %></td>
          <td><%= rate_podcast.name %></td>
          <td><%= rating_for rate_podcast, 'podcast', star: 5, path: '/images/ratyrate', disable_after_rate: true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class='rate_podcast_submit'>
  <input type="btn btn-default" value="Rate Podcasts" onClick="history.go(0)">
  </div>


<div class="container">
  
<div class="user-label"></div>
  <table>
    <thead>
      <tr>
        <th>Our Ratings</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @rate_podcasts.each do |rate_podcast| %>
        <tr>
          <td><%= image_tag rate_podcast.image.url(:thumb), :class => "img_thumb"  %></td>
          <td><%= rate_podcast.name %></td>
          <div class="readonly-star">
          <td><%= rating_for rate_podcast, 'podcast', { readonly: true}  %>
          </div>
          
          </td>
          <!--  <td><%= link_to 'Show', rate_podcast %></td> -->
          <% if can? :update, @rate_podcasts %>
           <td><%= link_to 'Edit', edit_rate_podcast_path(rate_podcast) %></td> 
           <% end %>
          <% if can? :delete, @rate_podcasts %>
          <td><%= link_to 'Destroy', rate_podcast, method: :delete, data: { confirm: 'Are you sure?' }%></td>
          <% end %> 
        </tr>
      <% end %>
    </tbody>
  </table>
  <h3 class="comments">See what the community is saying this week and add your own insights!</h3>
 <div class="col-md-12">
  <%= render 'disqus' %>
</div>
  <br>
</section>
<% if can? :create, @rate_podcasts %>
  <%= link_to 'New Rate Podcast', new_rate_podcast_path %>
<% end %>

app/views/rate_podcasts/new.html.erb
<h1>New Rate Podcast</h1>

<%= render 'form', rate_podcast: @rate_podcast %>

<%= link_to 'Back', rate_podcasts_path %>

app/views/rate_podcasts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Name:</strong>
  <%= @rate_podcast.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @rate_podcast.rating %>
</p>
<p>
	<%= rating_for @rate_podcast, 'podcast', star: 5, disable_after_rate: false, imdb_avg: true  %>
</p>

<%= link_to 'Edit', edit_rate_podcast_path(@rate_podcast) %> |
<%= link_to 'Back', rate_podcasts_path %>